repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.701
  hooks:
  - id: mypy
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
    language_version: python3
- repo: local
  hooks:
  - id: tests
    name: run tests
    language: system
    entry: pytest -v ./tests/
    pass_filenames: false
    # files: ^tests/.*$
